### ISSUE TITLE
Error code: 520 when uploading plugin from GitHub Actions

### ISSUE THREAD

**Issue by phborba** [opengisch/qgis-plugin-ci#105]
Hi guys, first of all, great job at your lib, it is very useful!

I've been trying to upload a new version of my plugin but I keep getting Error code: 520 from the QGIS plugin repository. Do you guys know what it is?

My error log of the GitHub Actions is here: https://github.com/dsgoficial/DSGToolsOp/runs/4763056433?check_suite_focus=true

**Comment by 3nids** [comment]
sorry for the silence.
feel free to re-open if the problem is still present
