### ISSUE TITLE
Several plugin ZIPs using QGIS Plugin CI have duplicated files inside

### ISSUE THREAD

**Issue by kannes** [opengisch/qgis-plugin-ci#111]
For some reason I downloaded all QGIS plugins and extracted them. I noticed an issue and it looks like QGIS Plugin CI is a common demoninator. If it is not the cause, sorry! :)

`resources.py` is included twice in 5 plugins:

- https://github.com/opengisch/qgis-swiss-locator/issues/36
- https://github.com/dsgoficial/DSGToolsOp/issues/36
- https://github.com/phborba/DeepLearningTools/issues/9
- https://forge.chapril.org/linux_alpes/caliec/ (no issue filed because no account)
- https://gitlab.com/Oslandia/qgis/qompligis (no issue filed because no account)

They all seem to use QGIS Plugin CI so I wonder if this is caused by some bug in it or misconfiguration at the plugin CIs?

**Comment by lbartoletti** [comment]
cc @Guts (for QompliGIS, I think I already spotted this issue for LSCI)

**Comment by 3nids** [comment]
Thanks for investigating this!
For swiss locator, I see resources.rc and resources_rc.py at the root?
Are you saying we should avoid shipping the .rc file?

**Comment by Gustry** [comment]
No, he means the `resources.py` file is duplicated in the ZIP : https://github.com/opengisch/qgis-swiss-locator/releases/download/1.4.6/swiss_locator.1.4.6.zip

**Comment by Gustry** [comment]
When it's extracted, one file is deleted by the OS, logical ...

**Comment by kannes** [comment]
I should add, this causes no issues when installing the plugins via QGIS's plugin installer. I guess it will just overwrite the duplicate.

This is mostly a cosmetic thing but it might be worth fixing for the sake of clean packaging. I only noticed it because I unpacked the ZIPs with standard archive tools.

**Comment by 3nids** [comment]
I guess the issue is when there is already one _rc.py file in the sources, which should not happen normally.

**Comment by 3nids** [comment]
![image](https://user-images.githubusercontent.com/127259/152529305-4353ae5e-33b7-466c-8322-8306224c173e.png)

**Comment by 3nids** [comment]
here is a proposal for a fix https://github.com/opengisch/qgis-plugin-ci/pull/112

**Comment by 3nids** [comment]
worked as expected
![image](https://user-images.githubusercontent.com/127259/154101805-38ecb639-4e53-4679-9222-71e4d8c1e4f1.png)
