### ISSUE TITLE
Transifex syncing fails on "404 The requested resource was not found on this server"

### ISSUE THREAD

**Issue by why-not-try-calmer** [opengisch/qgis-plugin-ci#196]
Example: https://github.com/opengisch/qgis-plugin-ci/actions/runs/4164246084/jobs/7205635060#step:6:96
Fix already PR'ed upstream: https://github.com/opengisch/pytransifex/pull/5.

**Comment by Gustry** [comment]
Thanks for looking in the issue.
It's not only the CI but also for production, we currently can't use transifex.

**Comment by why-not-try-calmer** [comment]
> Thanks for looking in the issue.
> It's not only the CI but also for production, we currently can't use transifex.

Okay, if you have more logs that might help get a better coverage of the issue(s), I am interested!

**Comment by Gustry** [comment]
It's exactly the same as in the test you show us, in the GitHub action. Transifex is failing on the `ping` method.

**Comment by why-not-try-calmer** [comment]
> It's exactly the same as in the test you show us, in the GitHub action. Transifex is failing on the `ping` method.

Ah cool, so the PR I mentioned in the above post should fix that.

**Comment by Gustry** [comment]
Yes, I was just saying it's not only impacting "CI tests" as written in the issue title ;-)
It's also on production with already tagged version of qgis-plugin-ci, just to rephrase :)
