### ISSUE TITLE
Copy LICENCE file from root directory to plugin package

### ISSUE THREAD

**Issue by jmkerloch** [opengisch/qgis-plugin-ci#255]
We have some issue when using latest version (qgis-plugin-ci-2.8.1): https://gitlab.com/Oslandia/qgis/qwc2_tools/-/jobs/5598167137#L306

```
$ qgis-plugin-ci release ${CI_COMMIT_TAG} --allow-uncommitted-changes --osgeo-username $OSGEO_USER_NAME --osgeo-password $OSGEO_USER_PASSWORD
2023-11-22 17:24:14||ERROR||release||=== A fault occurred occurred ===
Fault code: 1
Fault string: <Fault 1: 'File upload must be a valid QGIS Python plugin compressed archive. Cannot find LICENSE in plugin package.'>
```

This seems to come from this commit of QGIS plugin repository : https://github.com/qgis/QGIS-Django/commit/91b9576a53c6b75693427bb2a1dc9a2730a8282f

```
# Checks for LICENCE file precense
    licensename = package_name + "/LICENSE"
    if licensename not in namelist:
        raise ValidationError(_("Cannot find LICENSE in plugin package."))
```

Do you think we should copy LICENCE file from root directory to plugin package ? 

This will avoid a copy of the file in the CI.

**Comment by Gustry** [comment]
If the file exists in the root directory, I would say yes, let's package it.

**Comment by Guts** [comment]
I let a comment on the issue to ask for reverting this breaking change in favor of a more open community driven change process.

**Comment by m-kuhn** [comment]
I think this has become relevant again, a LICENSE file is required since June.

**Comment by Guts** [comment]
I've fixed that on my side. I try to push before the week-end.

**Comment by nirvn** [comment]
@Guts , just saw your comment in this issue _after_ opening the following PR (https://github.com/opengisch/qgis-plugin-ci/pull/307). Feel free to review that or supersede it with something better :)

**Comment by Guts** [comment]
> @Guts , just saw your comment in this issue after opening the following PR (https://github.com/opengisch/qgis-plugin-ci/pull/307). Feel free to review that or supersede it with something better :)

Hello @nirvn,

No worries. My delay have expired for some days already.  
Not sure to be able to do better :sweat_smile:. I'll have a look to your PR.
