### ISSUE TITLE
404 Error on deploy

### ISSUE THREAD

**Issue by vavpp** [opengisch/qgis-plugin-ci#297]
Hello,

I'm new to this ci publishing tool, and havent gotten it to work correctly.
I have added 2 secrets to my #respository 
![image](https://github.com/opengisch/qgis-plugin-ci/assets/105847038/564bcabf-7851-4ff5-a544-e5665d654820)

I'm experiencing a 404 as part of the deploy step:

   ```- name: Deploy plugin
        run: >-
          qgis-plugin-ci
          release ${GITHUB_REF/refs\/tags\//}
          --github-token ${{ secrets.GITHUB_TOKEN }}
          --osgeo-username ${{ secrets.OSGEO_USER }}
          --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
```
error:
```
Run qgis-plugin-ci release ${GITHUB_REF/refs\/tags\//} --github-token *** --osgeo-username *** --osgeo-password ***
  qgis-plugin-ci release ${GITHUB_REF/refs\/tags\//} --github-token *** --osgeo-username *** --osgeo-password ***
  shell: /usr/bin/bash -e {0}
  env:
    pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
  
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/qgis-plugin-ci", line 8, in <module>
    sys.exit(cli())
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qgispluginci/cli.py", line [2](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:2)22, in cli
    release(
  File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qgispluginci/release.py", line 55[3](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:3), in release
    is_prerelease = release_is_prerelease(
  File "/opt/hostedtoolcache/Python/3.8.18/x6[4](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:4)/lib/python3.8/site-packages/qgispluginci/release.py", line 3[5](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:5)1, in release_is_prerelease
    repo = Github(github_token).get_repo(slug)
  File "/opt/hostedtoolcache/Python/3.8.18/x[6](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:6)4/lib/python3.8/site-packages/github/MainClass.py", line 427, in get_repo
    headers, data = self.__requester.requestJsonAndCheck("GET", url)
  File "/opt/hostedtoolcache/Python/3.8.18/x[6](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:7)4/lib/python3.8/site-packages/github/Requester.py", line 53[7](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:8), in requestJsonAndCheck
    return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
  File "/opt/hostedtoolcache/Python/3.[8](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:9).18/x64/lib/python3.8/site-packages/github/Requester.py", line 5[9](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:10)8, in __check
    raise self.createException(status, responseHeaders, data)
github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest"}
```

Could anyone point me in the right direction?

**Comment by Gustry** [comment]
QGIS-Plugin-CI doesn't manage création of the GitHub release.
Did you create one ?
https://github.com/3liz/lizmap-plugin/blob/master/.github/workflows/ci.yml#L101

AFAIK it will only attach assets to it.

**Comment by vavpp** [comment]
> Hello,
> 
> 
> 
> I'm new to this ci publishing tool, and havent gotten it to work correctly.
> 
> I have added 2 secrets to my #respository 
> 
> ![image](https://github.com/opengisch/qgis-plugin-ci/assets/105847038/564bcabf-7851-4ff5-a544-e5665d654820)
> 
> 
> 
> I'm experiencing a 404 as part of the deploy step:
> 
> 
> 
>    ```- name: Deploy plugin
> 
>         run: >-
> 
>           qgis-plugin-ci
> 
>           release ${GITHUB_REF/refs\/tags\//}
> 
>           --github-token ${{ secrets.GITHUB_TOKEN }}
> 
>           --osgeo-username ${{ secrets.OSGEO_USER }}
> 
>           --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
> 
> ```
> 
> error:
> 
> ```
> 
> Run qgis-plugin-ci release ${GITHUB_REF/refs\/tags\//} --github-token *** --osgeo-username *** --osgeo-password ***
> 
>   qgis-plugin-ci release ${GITHUB_REF/refs\/tags\//} --github-token *** --osgeo-username *** --osgeo-password ***
> 
>   shell: /usr/bin/bash -e {0}
> 
>   env:
> 
>     pythonLocation: /opt/hostedtoolcache/Python/3.8.18/x64
> 
>   
> 
> Traceback (most recent call last):
> 
>   File "/opt/hostedtoolcache/Python/3.8.18/x64/bin/qgis-plugin-ci", line 8, in <module>
> 
>     sys.exit(cli())
> 
>   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qgispluginci/cli.py", line [2](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:2)22, in cli
> 
>     release(
> 
>   File "/opt/hostedtoolcache/Python/3.8.18/x64/lib/python3.8/site-packages/qgispluginci/release.py", line 55[3](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:3), in release
> 
>     is_prerelease = release_is_prerelease(
> 
>   File "/opt/hostedtoolcache/Python/3.8.18/x6[4](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:4)/lib/python3.8/site-packages/qgispluginci/release.py", line 3[5](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:5)1, in release_is_prerelease
> 
>     repo = Github(github_token).get_repo(slug)
> 
>   File "/opt/hostedtoolcache/Python/3.8.18/x[6](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:6)4/lib/python3.8/site-packages/github/MainClass.py", line 427, in get_repo
> 
>     headers, data = self.__requester.requestJsonAndCheck("GET", url)
> 
>   File "/opt/hostedtoolcache/Python/3.8.18/x[6](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:7)4/lib/python3.8/site-packages/github/Requester.py", line 53[7](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:8), in requestJsonAndCheck
> 
>     return self.__check(*self.requestJson(verb, url, parameters, headers, input, self.__customConnection(url)))
> 
>   File "/opt/hostedtoolcache/Python/3.[8](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:9).18/x64/lib/python3.8/site-packages/github/Requester.py", line 5[9](https://github.com/vavpp/riogisoffline/actions/runs/8630820526/job/23660536568#step:9:10)8, in __check
> 
>     raise self.createException(status, responseHeaders, data)
> 
> github.GithubException.UnknownObjectException: 404 {"message": "Not Found", "documentation_url": "https://docs.github.com/rest"}
> 
> ```
> 
> 
> 
> Could anyone point me in the right direction?

You can close this. I had not configured a release. It works as expected.
