### ISSUE TITLE
Changelog - Use header 2 (##) instead of 3 (###) for version numbers

### ISSUE THREAD

**Issue by Guts** [opengisch/qgis-plugin-ci#31]
Following https://keepachangelog.com/en/1.0.0/ as documented, the model should use headers level 2 for versions numbers, not 3 as set in the model https://github.com/opengisch/qgis-plugin-ci/blob/master/CHANGELOG.md.

In addition it'll match markdown rules (MD001/heading-increment/header-increment: Heading levels should only increment by one level at a time [Expected: h2; Actual: h3).

**Comment by Gustry** [comment]
Is header 2 not working ? 
I haven't tried, just checking the regexp : https://github.com/opengisch/qgis-plugin-ci/blob/master/qgispluginci/parameters.py#L9

You can customize the regexp by adding the expression you want in your `setup.cfg` : 
https://github.com/opengisch/qgis-plugin-ci/blob/master/qgispluginci/parameters.py#L62

And there is a link to https://regex101.com/r/PXoYSs/4 which is using header 2. So there is something indeed which should work.

> following nearly the https://keepachangelog.com/en/1.0.0/

Sorry ;-)

**Comment by Guts** [comment]
Yes, sure, I think it's just to improve the docs.
Speaking of docs, what about a real documentation on RTD with full options described?

**Comment by Gustry** [comment]
> Use header 2 (##) instead of 3 (###) for version numbers

Done, I have updated the file.

There is still a empty title at the bottom of the file, it's needed if the changelog has less than 3 entries ! 🤫 (bad regexp)

**Comment by Guts** [comment]
> Done, I have updated the file.

Thanks! FYI I've also worked on this with different goal: move the file you modified as test fixture and create the real project changelog at the root. I create a specific issue for this.

> There is still a empty title at the bottom of the file, it's needed if the changelog has less than 3 entries ! shushing_face (bad regexp)

I've almost a new regexp avoiding this issue too. But I'll need more time to achieve it properly.

**Comment by Gustry** [comment]
I think we can close this one :)
