### ISSUE TITLE
Handle semantic versioning also for pre-release (beta/alpha/...) and to automate the experimental flag

### ISSUE THREAD

**Issue by Guts** [opengisch/qgis-plugin-ci#32]
:clap:  Thanks for this project, it's really useful. :clap: 

# Global description

I'm trying to respect [SemVer](https://semver.org/) to name my plugins versions: 1.0.0, 1.1.2, 1.2.0-beta1, etc.  
But using qgis-plugin-ci on [pre-release versions](https://semver.org/#spec-item-9) is not working as expected.

# Reproduce the actual behavior

To reproduce, consider a changelog like this:

```markdown
# Changelog

## 0.3.0-beta1 - 2021/02/08

- Documentation refactoring
- Use modern workflow to package and release the plugin
- Minor code changes

## 0.2.2 - 2020/12/23

- Navidad version
- QGIS 3.18 compatibility
```

Running `qgis-plugin-ci package 0.3.0-beta1` runs without any warnings but into the `metadata.txt`:

```ini
# Uncomment the following line and add your changelog:
changelog=
 Version 0.2.2:
 - Navidad version
 - QGIS 3.18 compatibility
```

# Expected behavior

How I imagine the workflow:

1. Valid the version against SemVer (using something like [that](https://python-semver.readthedocs.io/)). It could be disabled by an option flag for those who are not using the semantic versioning (weird people I guess :wink: )
2. If pre-release, then apply experimental flag in metadata.txt
3. Enjoy the magic :mage:

**Comment by 3nids** [comment]
@Gustry can I have your 👀  on this?

**Comment by Gustry** [comment]
I have indeed didn't think/plan to support full (I mean with -beta, -pre etc) semver when I wrote the regexp :)

**But** ...
I was expecting that someone will come later with a different changelog format :)
And @Guts it's you :)

That's why I made it customizable without any code update in qgis-plugin-ci.

You need to add a line in your `setup.cfg` (or `.qgis-plugin-ci`) with `changelog_regexp` : 
https://github.com/opengisch/qgis-plugin-ci/blob/master/qgispluginci/parameters.py#L60

The regepx can be fixed upstream in https://github.com/opengisch/qgis-plugin-ci/blob/master/qgispluginci/parameters.py#L9
It was quite fragile, but this file
https://github.com/opengisch/qgis-plugin-ci/blob/master/CHANGELOG.md
is covered by unittest.

**Comment by Gustry** [comment]
> Running qgis-plugin-ci package 0.3.0-beta1 runs without any warnings but into the metadata.txt:

True, a warning could have been raised.

But I didn't want to fail a packaging just because someone wrote a dodgy changelog or the regepx is too strict to include the changelog in the metadata.txt (I don't thing that including the changelog is critical when packaging).

**Comment by Guts** [comment]
> That's why I made it customizable without any code update in qgis-plugin-ci.

Nice. I'll have a look.

> True, a warning could have been raised.
> But I didn't want to fail a packaging just because someone wrote a dodgy changelog or the regepx is too strict to include the changelog in the metadata.txt (I don't thing that including the changelog is critical when packaging).

Sure, I totally agree. IMHO, that's why a warning exists: warnt he user without breaking anything.


> If pre-release, then apply experimental flag in metadata.txt

And what do you think about my proposal to apply expertimental flag on prerelease tag?

**Comment by Guts** [comment]
On the regex link (https://regex101.com/r/PXoYSs/4), I see that the second element is not matched:

![image](https://user-images.githubusercontent.com/1596222/107241534-5a890800-6a2b-11eb-9bb8-6826c25ac9e7.png)

And I don't get why not. Am I missing something?

**Comment by Guts** [comment]
FYI, I'm working on this: https://regex101.com/r/6OchHd/1

**Comment by Gustry** [comment]
> And what do you think about my proposal to apply expertimental flag on prerelease tag?

Sure good idea !

> And could i be added to the documentation?

Of course !

For the changelog parser, look here : https://github.com/opengisch/qgis-plugin-ci/blob/master/qgispluginci/changelog.py
And tests : https://github.com/opengisch/qgis-plugin-ci/blob/master/test/test_changelog.py

**Comment by Guts** [comment]
> On the regex link (https://regex101.com/r/PXoYSs/4), I see that the second element is not matched:
> 
> And I don't get why not. Am I missing something?

Ok got it, this is because of the hyphens in date instead of slashs. So it doesn't comply with Keep A Changelog convention:

> Confusing Dates
> 
> Regional date formats vary throughout the world and it's often difficult to find a human-friendly date format that feels intuitive to everyone. The advantage of dates formatted like 2017-07-17 is that they follow the order of largest to smallest units: year, month, and day. This format also doesn't overlap in ambiguous ways with other date formats, unlike some regional formats that switch the position of month and day numbers. These reasons, and the fact this date format is an ISO standard, are why it is the recommended date format for changelog entries. 

Right @Gustry ?

**Comment by Gustry** [comment]
You can make it compatible indeed. (for both hyphens and slashs would be top otherwise it will break existing plugin not using a pinned version of qgis-plugin-ci)

I would happily switch to the format they recommend ;-)

**Comment by Guts** [comment]
> (for both hyphens and slashs would be top otherwise it will break existing plugin not using a pinned version of qgis-plugin-ci)

I'll do my best but regex is not exactly my :tea: (yes, I'm stiil a human)! About the unpinned version: this is how we learn to always pin them :wink: !

**Comment by Gustry** [comment]
> I'll do my best but regex is not exactly my tea (yes, I'm stiil a human)!

Exactly the same feeling, this regepx wasn't my cup of tea :D 

That's why I was expecting someone will come later to improve this changelog parser ;-)
I just made it work for my use case and at that time, I didn't though about adding `-beta` to a version.
